### ISSUE TITLE
Mark items as read / visited

### ISSUE THREAD

**Issue by SeriousM** [housseindjirdeh/angular2-hn#20]
That would be very helpful!

**Comment by hdjirdeh** [comment]
Agreed! It can be as simple as have a lighter gray font color for the title text.

**Comment by zachberger** [comment]
I can take a look at this. I'm thinking of storing `item.id` in `localStorage` then applying the stypes you suggested above. Other HN apps also keep track of comments that have been viewed. Do you see #20 including this functionality?

**Comment by hdjirdeh** [comment]
Thank you!! Hmm not sure if we need to go to the lengths of using `localStorage`, I think a simple `:visited` CSS selector should do the trick?

That would be awesome but I wouldn't worry about that, we can close this with just story title links for now and open a separate issue for that (not sure how we would go about that too to be honest, maybe `localStorage` would be necessary in that case?).

**Comment by zachberger** [comment]
I think `:visited` will work to mark the `Story`'s  link as visited, however often times I skip the story's link and just view the comments. I would expect that this case would mark the `Story` as viewed. The `:visited` CSS selector wouldn't catch this case. 

I would propose that when a `Story`'s link is clicked on or when a `Story`'s comments are an entry is created in `localStorage` for that `Story` and the CSS on `stories.component` reflects that either of those locations are visited.

**Comment by hdjirdeh** [comment]
I see, my apologies I thought @SeriousM was referring to the story link being visited.

**Comment by zachberger** [comment]
@SeriousM's request could be limited to just the story link being visited, but looking holistically, i think it would be good to include both functionalities.

**Comment by hdjirdeh** [comment]
Yeah I was just thinking that actually, it would be nice to have that feature as well

In that case you're right, I can't think of another way other than using `localStorage`. However, I would still prefer that the item title text having a lighter gray font color applies to the actual link being visited (`:visited`). 

Maybe we can do the same thing with the `X comments` link that routes the user to `item.comments.component`. Give that a lighter shade if the item's comments have been viewed?

**Comment by hdjirdeh** [comment]
Or another thing we can do is give the `li` a slightly different tint. Something like this:

![image](https://cloud.githubusercontent.com/assets/12476932/21560834/c12d2814-ce32-11e6-8e91-bdf86d6f964a.png)

But don't worry too much about that for now, we can change where apply the CSS once we actually get the logic.

Again, thanks for helping. Genuinely appreciate it!

**Comment by SeriousM** [comment]
The visit state should be enough. It's just to see if I've seen this item
or not. I guess graying the title is better than changing the background.

**Comment by hdjirdeh** [comment]
@SeriousM Thanks mate.

@zachberger Let's leave this ticket with just the visited state of the story link. I'm open to having a separate ticket for showing the user when the story's comments have been visited (as I think this will be pretty useful as well).

**Comment by bbrks** [comment]
PR open for styling visited story links at #41

**Comment by housseindjirdeh** [comment]
Thanks again @bbrks, and I apologize for not merging your PR sooner
