### ISSUE TITLE
Ability to increase font size/line spacing

### ISSUE THREAD

**Issue by housseindjirdeh** [housseindjirdeh/angular2-hn#25]
Would be nice to have a littles settings icon that the user can click and change the font size of the page and/or line-spacing. Can be something similar to how they did it in this client https://react-hn.appspot.com or something slightly different. Open to suggestions :)

**Comment by housseindjirdeh** [comment]
Already added a settings section, now it's just a matter of adding a font toggle to it

**Comment by housseindjirdeh** [comment]
Cheers @Antogin, I should have closed this issue a long time ago thanks to your PR :)

**Comment by Antogin** [comment]
Np! i was wondering :)
