### ISSUE TITLE
Share functionality

### ISSUE THREAD

**Issue by housseindjirdeh** [housseindjirdeh/angular2-hn#32]
@SeriousM mentioned that it would be great have the ability to share story links or the comment's page for a story. Would love to get some suggestions on whether anyone thinks this is something we definitely need and if so, how/what should we implement exactly. 

Sending by mail should be simple, but should we include other avenues (social media) as well? Integration with Pocket has been mentioned, but not sure if we should spend time wrestling it's API if not too many people use it.

**Comment by SeriousM** [comment]
Can't we just open the share dialog from Android? That would simplify the
process a lot!
Benefits:
The webpage version  is using the share dialog from the browser.
The app version is using the native share dialog.

**Comment by hdjirdeh** [comment]
I see, yeah that would be neat actually but I'm not sure if it's possible. Will definitely look into it as it can make sharing super simple.

**Comment by housseindjirdeh** [comment]
Don't think this might be possible so will close this for now. If someone thinks there's a simple way to open the native share dialog on Android we'll reopen it!
