### ISSUE TITLE
Why you didn't use css framework ,?

### ISSUE THREAD

**Issue by Rebaiahmed** [housseindjirdeh/angular2-hn#38]
what's the advantages of using your own css files or SASS ?

**Comment by housseindjirdeh** [comment]
To be honest the styling for this app really isn't that complex at all, so I didn't need a framework like bootstrap to get going. Also, I use a service worker to 'precache' all the styles (along with HTML and JS static resources) so to have an entire framework with that could definitely slow things down. 

Even without the use of a service worker, if I could minimize the amount of assets needed for the app than why not, especially if the styles are pretty simple :)
