### ISSUE TITLE
what this `+variable ` syntax means?

### ISSUE THREAD

**Issue by inter-action** [housseindjirdeh/angular2-hn#39]
I am reading your code, but what is this syntax means? like the line down below
` this.pageNum = params['page'] ? +params['page'] : 1;`

**Comment by blackpr** [comment]
That is called [Conditional Operator](https://developer.mozilla.org/el/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) or Ternary Operator
It is just an if/else statment

```js
if (params['page']) {
  this.pageNumb = +params['page'];
} else {
  this.pageNumb = 1
}
```

the plus sign (+) at ``+params['page'] `` turns the value to number

**Comment by inter-action** [comment]
@blackpr thx 👍

**Comment by housseindjirdeh** [comment]
Thank you @blackpr, I appreciate it :)

@inter-action if you have any more questions please don't hesitate to ask!

**Comment by inter-action** [comment]
@housseindjirdeh yeah, I will :)
