### ISSUE TITLE
Investigate support for Angular view compiler

### ISSUE THREAD

**Issue by addyosmani** [housseindjirdeh/angular2-hn#53]
It's been so great seeing how far this has come since you started [adding](https://twitter.com/hdjirdeh/status/813866290993577984) sw-toolbox and sw-precache. Glad the suggestions were useful :)

On desktop, you're doing pretty well on our latest version Lighthouse as you know:

![screen shot 2017-03-06 at 9 55 39 pm](https://cloud.githubusercontent.com/assets/110953/23643671/0abeed00-02b8-11e7-95c3-62211b53254c.jpg)

Seems like [switching](https://twitter.com/hdjirdeh/status/808148804675440640) to [AoT support](https://twitter.com/addyosmani/status/798040007361511425) made a nice little dent :)

If you wanted to get those time to interactive numbers down further, you might consider trying out the new view compiler that landed in Angular master: 

https://twitter.com/robwormald/status/834938328294154240

Are you using H/2 Server Push? (saw some related commits in master)

**Comment by housseindjirdeh** [comment]
Genuinely can't thank you enough providing so many suggestions (App Shell + dynamic model + AoT + this). I owe you one mate :)

Yes thank you for this, will definitely get to it using the new compiler this week to cut down the app size. 

And yep I just recently added h2 push by preloading all the primary bundles (non-lazily loaded) in [firebase.json](https://github.com/housseindjirdeh/angular2-hn/blob/master/firebase.json#L19). Pretty sure there's probably a better way to do this then hardcoding the bundle names so will need to look into that as well.

<img width="1073" alt="screen shot 2017-03-07 at 1 38 58 pm" src="https://cloud.githubusercontent.com/assets/12476932/23672079/7f600bca-033b-11e7-9e1f-602cfe42f5cc.png">

Another thing is that with h2 server push, way smaller bundle chunks would probably make more sense. So I've been thinking of trying to include [AggresiveSplittingPlugin](https://medium.com/webpack/webpack-http-2-7083ec3f3ce6#.5448lujih). However it seems to still be experimental, so firstly using the new view compiler is definitely the first step.

**Comment by housseindjirdeh** [comment]
Just upgraded to 4.0.0-rc.2 (new view engine landed in 4.0.0-rc.1). 

~150K script gzipped down to 126KB. Not bad at all!
