### ISSUE TITLE
ServiceWorker registration failed:  DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

### ISSUE THREAD

**Issue by jose2007kj** [housseindjirdeh/angular2-hn#59]
sir,thanks for this awesome project..........the app opens successfully but i get this message in console i am running the code with `ng serve host MYIP `

**Comment by jose2007kj** [comment]
i got it working while following the below steps
1)ng build --prod --aot
2)npm run precache
3)npm install live-server --save-dev
4)npm run static-serve
5)ng serve

sir,if i did't follow step 3,4 then i get `ServiceWorker registration failed:  TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
Navigated to http://localhost:4200/`       also i notice that dist file is getting removed while doing ng serve

**Comment by jose2007kj** [comment]
i think https is required...going to check with firebase....................https://houssein.me/continuous-integration-angular-firebase-travisci

**Comment by jose2007kj** [comment]
working fine when deployed in firebase

**Comment by housseindjirdeh** [comment]
Apologies for not getting back to you sooner! You're right, HTTPS is required and that's why that warning was thrown :)

**Comment by jose2007kj** [comment]
no problem sir,.......................thanks .....your tutorials and this opensource project is really helpful

**Comment by housseindjirdeh** [comment]
Cheers :) I'm glad you find them so helpful!

**Comment by Ganeshjee02** [comment]
please help me to how to use push notification in angular cli project

**Comment by jose2007kj** [comment]
@Ganeshjee02 bro please see this link....... it seems to have some information u require

**Comment by adarshvsukumaran** [comment]
@jose2007kj 
Hi, in Firebase how can run server.js. [In localsystem, we have to use 'node server.js' command in CLI]. I have deployed my code in Firebase. But when i run the code, i am getting this error. "WebSocket connection to 'ws://localhost:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED"
