### ISSUE TITLE
Windows doesn't scroll back to top when openning a item

### ISSUE THREAD

**Issue by Antogin** [housseindjirdeh/angular2-hn#60]
When a item is opened from the bottom of the page, the page doesn't scroll back to top in the item detail view.

(sorry , co workers are very picky, opening a PR right now)

**Comment by housseindjirdeh** [comment]
Thanks for this!! Wow I'm surprised I didn't catch this, I think it must have been handled at one point but some refactoring may have removed it.

Thanks again mate, appreciate it!
