### ISSUE TITLE
Simple question for devs

### ISSUE THREAD

**Issue by tsmith-sdm** [housseindjirdeh/angular2-hn#62]
Why

`declare var fetch;`

in hackernews-api.service.ts?

**Comment by housseindjirdeh** [comment]
Thanks for asking this :) it's an ambient declaration which means we're telling the TypeScript compiler '_don't worry about not being able to recognize fetch, it exists_'

However since `isomorphic-fetch` adds fetch as a global, we really don't need that line so I removed it!
