### ISSUE TITLE
Consider using link rel=preload to improve performance

### ISSUE THREAD

**Issue by addyosmani** [housseindjirdeh/angular2-hn#63]
Checking the latest deployment (https://angular2-hn.firebaseapp.com/) over normal 3G, performance is great but a lot of our JS work doesn't get completed until much later on: https://www.webpagetest.org/video/compare.php?tests=170514_00_bb389f33405b558ea644b37f565c8a56-r:1-c:0 

I wonder if it would be worth adding in support for `<link rel="preload">` so you can tell the browser early on that the following scripts are important:

```
<script type="text/javascript" src="inline.e195cb797c8ab56372da.bundle.js"></script>
<script type="text/javascript" src="vendor.a39b96651e0f11f342a5.bundle.js"></script>
<script type="text/javascript" src="main.f85b553fbaef45424581.bundle.js"></script>
```

I've suggested this to a number of sites where it has improved their time to interactivity (it hasn't for everyone) but it might be worth giving a shot.

I might separately also suggest registering SW after the window onload event so that there's no chance of network contention with the main page resources on first load: https://github.com/housseindjirdeh/angular2-hn/blob/master/src/index.html#L62

**Comment by housseindjirdeh** [comment]
Thanks so much for the suggestions mate <3

1. I really didn't realize that deferring SW registration after window load could be significant, but thinking about it and looking at the network traffic ---> it makes sense. Thank you for noticing that! Pushed that change up: https://github.com/housseindjirdeh/angular2-hn/commit/659912e6676bdc0b195e74193a68d60a2f35fb0d
2. Looking at ways to include `preload`, I guess it's a good as time as ever to eject and modify the Webpack config. I just did and included `PreloadWebpackPlugin` to generate preload tags for the main 3 bundles (https://github.com/housseindjirdeh/angular2-hn/commit/548d0e3d40fcf34d03a7dffb9f126651ee3e06b1#diff-11e9f7f953edc64ba14b0cc350ae7b9dR233). You should see those scripts being preloaded in the app now.

The next thing I need to do is run a few WPT tests on the app with 3G and let you know the improvements. Will do that tomorrow morning :)

**Comment by addyosmani** [comment]
> The next thing I need to do is run a few WPT tests on the app with 3G and let you know the improvements. Will do that tomorrow morning :)

Awesome :) Looking forward to seeing if it made an improvement! Thanks for considering these small perf suggestions, @housseindjirdeh!

**Comment by housseindjirdeh** [comment]
Ran a couple of test, unfortunately doesn't look like it gave some wins 😢 . Numbers are looking slightly higher for some reason actually but I'm assuming its fluctuation.

Spent some time last night trying to set up [`AggressiveSplittingPlugin`](https://github.com/webpack/webpack/tree/master/examples/http2-aggressive-splitting) and leveraging Firebase's H2 push support but unfortunately it doesn't work with HTMLWebpackPlugin as of now (see [here](https://github.com/jantimon/html-webpack-plugin/issues/446)). Will definitely give that a shot once it's supported in case it can improve performance (but not sure if it would).

**Comment by housseindjirdeh** [comment]
Opened #67 to track h2 push
