### ISSUE TITLE
You should build with AOT 

### ISSUE THREAD

**Issue by MRHarrison** [housseindjirdeh/angular2-hn#64]
It doesn't seem like you are leveraging a benefit of angular which is AOT and affecting the performance numbers.

I see you are using [npm build](https://github.com/angular/angular-cli/wiki/build), but perhaps not the right build which should be ng build --target=production --environment=prod --aot

**Comment by housseindjirdeh** [comment]
Thanks for this @MRHarrison! So I [ejected](https://github.com/angular/angular-cli/wiki/eject) the app which allowed me to modify the webpack configurations. The reason I did that was to add support for preloading the main scripts of the application with `<link rel="preload">` by using [PreloadWebpackPlugin](https://github.com/housseindjirdeh/angular2-hn/blob/master/webpack.config.js#L233-L237) as well as give me more flexibility to modify our build output in the future.

Once ejected, regular build commands don't work anymore hence why you're noticing `npm build` as the build command. However, I did eject with `ng eject --aot` which means the ejected build should have AOT compilation included.

**Comment by paulogr** [comment]
Are you sure of that?

Because your main.ts file is using `platformBrowserDynamic` (JIT) and according angular docs you need to user `platformBrowser` for AOT

Take a look
https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#bootstrap

I'm almost sure you haven't compiled with AOT since you'd eject from Angular CLI.

**Comment by MarkPieszak** [comment]
Ngtools/webpack automatically creates a different file based off that one which uses platformBrowser (not dynamic) and imports the NgFactoryModule as well. 

Magic 👺

**Comment by housseindjirdeh** [comment]
Cheers @MarkPieszak, was just about to say there's some magic behind the scenes and I'm pretty sure that with apps using CLI builds - we shouldn't be modifying the `main.ts` according to that documentation. But wasn't sure that `ngtools/webpack` does the magic so thanks for clearing that up :)

@paulogr thanks for bringing that up however <3, there may definitely be things like that I missed so please don't hesitate to share your thoughts if you think I have

**Comment by paulogr** [comment]
Uow, I didn't realize that!

Thank you guys for that information!

**Comment by MarkPieszak** [comment]
Anytime 🍻 

Yeah without it, you'd need 2 tsconfigs, 2 main.browser files, etc. 
A PR went through to handle it for main.server files (in the Universal use-case as well), not sure if it's been published to npm yet though.
